project:
  type: book
  output-dir: docs

book:
  title: "Bet Mitzvah"
  author: "Max Chiswick"
  date: "9/11/2024"
  cover-image: cover.png
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd

    - part: intro.qmd

    - part: "CHAPTER 1"

    - part: "CHAPTER 2"

    - part: "CHAPTER 3"

    - part: "CHAPTER 4"

    - part: "CHAPTER 5"

    - part: "CHAPTER 6"

    - part: "CHAPTER 7"

    - part: "CHAPTER 8"

    - part: "CHAPTER 9"

    - part: "CHAPTER 10"

    - part: "CHAPTER 11"

    - part: "CHAPTER 12"

    - part: "CHAPTER 13"

bibliography: references.bib

format:
  html:
    theme: cosmo
    math: true 
    toc: true
    toc-expand: true
    mathjax: 
      config: 
        text: 
          inlineMath: [['$', '$'], ['\\(', '\\)']]
  pdf:
    documentclass: scrreprt


